# Generated by Django 2.2.7 on 2019-11-17 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_remove_meal_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='image_url',
            field=models.CharField(default='acb', max_length=60),
            preserve_default=False,
        ),
    ]
