# Generated by Django 2.2.7 on 2019-11-11 22:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0002_auto_20191111_0018'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='time',
        ),
        migrations.AddField(
            model_name='reserve',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reserve',
            name='hour',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
