# Generated by Django 2.2.7 on 2019-11-13 17:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0004_auto_20191112_0124'),
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.IntegerField()),
                ('min_person', models.IntegerField()),
                ('max_person', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='reserve',
            name='person',
            field=models.IntegerField(default=1, validators=[django.core.validators.MaxValueValidator(10), django.core.validators.MinValueValidator(1)], verbose_name='Number of diners'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='reserve',
            name='hour',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(8), django.core.validators.MinValueValidator(0)], verbose_name='Time(0~8, means 0 p.m. ~ 8 p.m.)'),
        ),
    ]
