# Generated by Django 2.2.7 on 2019-11-13 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0005_auto_20191113_1252'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='table',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='reserve.Table'),
            preserve_default=False,
        ),
    ]
