# Generated by Django 2.2.7 on 2019-11-13 19:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0006_reserve_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='name',
            field=models.CharField(default='abc', max_length=200, validators=[django.core.validators.MinLengthValidator(2, 'Your name must be greater than 2 characters')]),
            preserve_default=False,
        ),
    ]
