# Generated by Django 2.2.7 on 2019-11-13 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0007_table_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='table',
            name='number',
        ),
    ]
