# Generated by Django 2.2.7 on 2019-11-14 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0009_auto_20191113_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserve',
            name='hour',
            field=models.IntegerField(choices=[(11, '11:00'), (21, '21:00')], verbose_name="Time you'll arrive"),
        ),
    ]
