# Generated by Django 2.2.7 on 2019-11-14 03:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0010_auto_20191113_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='reserve.TableType'),
            preserve_default=False,
        ),
    ]
