# Generated by Django 2.2.7 on 2019-11-30 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0013_auto_20191115_1256'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserve',
            name='phone',
            field=models.CharField(default='1456', max_length=20),
            preserve_default=False,
        ),
    ]
