# Generated by Django 2.2.7 on 2019-12-03 00:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0014_reserve_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='date',
        ),
        migrations.RemoveField(
            model_name='reserve',
            name='hour',
        ),
        migrations.AddField(
            model_name='reserve',
            name='reserve_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
