# Generated by Django 2.2.7 on 2019-12-03 00:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0015_auto_20191202_1925'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reserve',
            old_name='reserve_time',
            new_name='time',
        ),
    ]
