# Generated by Django 2.2.7 on 2019-12-05 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reserve', '0016_auto_20191202_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reserve',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='reserve',
            name='person',
            field=models.IntegerField(verbose_name='Number of diners'),
        ),
    ]
